### ISSUE TITLE
Difference between registry values and registry keys in Sigma

### ISSUE THREAD

**Issue by rfackroyd** [SigmaHQ/sigma#3116] opened 2022-06-09 16:42 UTC
I have an issue which relates quite closely to [this pull request](https://github.com/SigmaHQ/sigma/pull/1820).

Taking a look at the accepted Sigma rules, `TargetObject` is currently used to describe both the registry key and value together, with `Details` consistently referring to the data stored under a given registry value.

Taking a look at some rules, it seems like `TargetObject|endswith` is used to denote a registry value - [example](https://github.com/SigmaHQ/sigma/blob/73c6bea167824eb111fef2159f1e7d7c1acf03be/rules/windows/registry/registry_set/registry_set_creation_service_temp_folder.yml)

However in other cases it is a combination of key and value - [example](https://github.com/SigmaHQ/sigma/blob/e36c6469335ba264dbee31f4c2c53db954ca678d/rules/windows/registry/registry_set/registry_set_set_servicedll.yml)

When converting Sigma to Carbon Black land this doesn't matter, as key and value are both queried under the same `regmod_name` identifier. Therefore, the Carbon Black backend can map `TargetObject` to `regmod_name` no problem.

However, Microsoft Defender for Endpoint (mdatp) does discern between the two, so when it receives a `TargetObject`, the backend does not know whether this is a registry value or a registry key.

[I can see this has been addressed in the Microsoft DfE backend](https://github.com/SigmaHQ/sigma/blob/eec218e82b6ed46e550a324154acd98341c99cca/tools/sigma/backends/mdatp.py#L122), I could use `ObjectValueName` to denote registry values, however these Sigma rules will now struggle to be converted to other syntaxes which do not acknowledge `ObjectValueName` as an applicable field for conversion in their respective configurations & backends. As referred to above, `TargetObject|endswith` is also used interchangeably, so it is not a suitable candidate to represent registry values.

Please let me know if I am missing something fundamental here, but I am struggling to see how to distinguish between registry values and keys in a way that works for multiple backends.

**Comment by frack113** [comment] 2022-06-09 17:08
Hi,
- Sigma rule is universal and it is not written for a  backend/SIEM
- Sigma rule use original field name from the event only (here sysmon)

Elastic beat split too some original fields so get the same trouble.

If sysmon X introduced something like  `TargetKey` and `TargetValue` some day , Sigma rule will use it of course.
if you open a petition at MS to have it , I sign it. 😄

**Comment by Neo23x0** [comment] 2022-06-09 18:17
I guess that this could be handled in the new pySigma @thomaspatzke as soon as someone wrote a backend for Carbon Black

**Comment by Neo23x0** [comment] 2022-06-09 18:25
But I see the problem. It would probably be much better to have these values in two different fields, because merging is much easier than splitting.

**Comment by thomaspatzke** [comment] 2022-06-09 18:33
> I guess that this could be handled in the new pySigma (CC @thomaspatzke) as soon as someone wrote a backend for MDATP
> 
> I'm not sure if field values can be split up into two field values.

It will be possible based on regular expression patterns. Anyways,

> But I see the problem. It would probably be much better to have these values in two different fields, because merging is much easier than splitting.

I think this is the cleaner option.

**Comment by Neo23x0** [comment] 2022-06-21 14:15
Yes, someone would have to rework all the registry rules and check the backend support.

**Comment by nasbench** [comment] 2022-12-28 11:02
Closing this as answered/won't fix for now since the issue is a lot trickier to fix and it's out of our hands for the moment.

- As @Neo23x0 someone needs to go fix all reg rules (which is practically impossible) since the context is lost once you combine the reg value+key
- Also it makes it harder to write rules if the source doesn't do this by default (for example Sysmon. Which most people use to collect reg values). We all need to use for example EID 4657 who does this split in the event.
- To make it work we also need to use a non-default field name which is confusing and goes against the ethos of SIGMA which aims to make it as painless as possible to translate/write rules
- Finally, needs a big change to all backends here in SIGMA to support this.

**Closed by nasbench** 2022-12-28 11:02 UTC
