### ISSUE TITLE
Fieldmapping issue in config file

### ISSUE THREAD

**Issue by ishusoka** [SigmaHQ/sigma#3243] opened 2022-07-18 11:55 UTC
Hello,

I encountered an issue when configuring a custom fieldmapping for the translation of Sigma rules to Splunk Query.
I can't manage SIEM parsing, that why i configured fieldmapping.

I used this rule to show my issue : 
[registry_set_abusing_windows_telemetry_for_persistence.yml](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_abusing_windows_telemetry_for_persistence.yml)

For my mapping i have something like : 
`
CommandLine:
    category=network_connection: network_command_line
    category=image_load: image_command_line
    category=registry_set: registry_command_line
    default: command_line
`
When fields are used in "fields" section, but no in the detection part, the fieldmapping isn't correctly applied.
It's the default fieldmapping this is applied.

In our rule, the field CommandLine is used in the fields section, but not in the detection.
As the rule is a registry_set, the field should be mapped to **registry_command_line**, but when i performed translation, it's mapped to **"command_line"**

```
(EventType="SetValue" registry_full_key="*HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\TelemetryController\\*" (registry_data="*.sh" OR registry_data="*.exe" OR registry_data="*.dll" OR registry_data="*.bin" OR registry_data="*.bat" OR registry_data="*.cmd" OR registry_data="*.js" OR registry_data="*.ps" OR registry_data="*.vb" OR registry_data="*.jar" OR registry_data="*.hta" OR registry_data="*.msi" OR registry_data="*.vbs")) 
| table EventID,command_line,registry_full_key,registry_data
```

So, i decide to add a condition that use the commandline field.
![image](https://user-images.githubusercontent.com/29402891/179505482-8f17c5fa-3e41-463d-9332-10b040b94dee.png)

After translation, the fieldmapping is correctly setup.

![image](https://user-images.githubusercontent.com/29402891/179505840-76143df4-450b-4b68-90c1-d9eab8c7ff9e.png)

Is it a bug ?
Thank you in advance,
Ishu

**Comment by frack113** [comment] 2022-12-20 11:59
HI , there are no commandline in registry event.
So not not a bug.

**Comment by nasbench** [comment] 2022-12-20 12:40
Hi, 

As @frack113 said this is not a bug a small misunderstanding and a small error in the `rule`.

The `fields` field you see being used in the rule is just a field that lists some of the most interesting fields to look at during an investigation (You can check the [definition in the specification](https://github.com/SigmaHQ/sigma-specification/blob/e2e347180fdd64417cd7c1f08d661837f378c439/Sigma_specification.md#fields)).

Basically, It means if you have this rule trigger it's better to check X, Y, and Z fields for more context.

In this case, the typo was the addition of the `CommandLine` field (since it's not available by default in a `registry_set` event) and this will be fixed in a future commit.

Finally, to answer your question regarding mapping. When you convert a rule using `sigmac` the mappings are chosen from the [config folder](https://github.com/SigmaHQ/sigma/tree/master/tools/config) as you figured out and not from the `fields` field.

Hope this clears things up for you. If you have other issues don't hesitate to open a new issue :)

**Closed by nasbench** 2022-12-20 12:40 UTC
