### ISSUE TITLE
Sigmac Failure (No Error Message) - Unsupported Feature

### ISSUE THREAD

**Issue by leegengyu** [SigmaHQ/sigma#2848] opened 2022-03-24 07:59 UTC
Hi there,

I am facing a failure situation when running Sigmac, with no error message seen.

To replicate the issue:
1. Clone the current repository (I cloned the version whose last commit has an ID of `a90148c4141f139b1234a6943da4d5178e22bc4a`).
2. Run the following command (within `rules/` directory) to remove rules which Sigmac cannot convert, due to `-t es-rule` parameter in `sigmac` command:

```
rm windows/builtin/security/win_rare_schtasks_creations.yml
rm windows/builtin/security/win_susp_failed_logons_explicit_credentials.yml
rm windows/builtin/security/win_susp_failed_logons_single_process.yml
rm windows/builtin/security/win_susp_failed_logons_single_source.yml
rm windows/builtin/security/win_susp_failed_logons_single_source_kerberos.yml
rm windows/builtin/security/win_susp_failed_logons_single_source_kerberos2.yml
rm windows/builtin/security/win_susp_failed_logons_single_source_kerberos3.yml
rm windows/builtin/security/win_susp_failed_logons_single_source_ntlm.yml
rm windows/builtin/security/win_susp_failed_logons_single_source_ntlm2.yml
rm windows/builtin/security/win_susp_failed_logons_single_source2.yml
rm windows/builtin/security/win_susp_failed_remote_logons_single_source.yml
rm windows/builtin/security/win_susp_multiple_files_renamed_or_deleted.yml
rm windows/builtin/security/win_susp_samr_pwset.yml
rm windows/builtin/system/win_rare_service_installs.yml
rm windows/builtin/taskscheduler/win_rare_schtask_creation.yml
rm windows/dns_query/dns_query_win_possible_dns_rebinding.yml
rm windows/image_load/image_load_mimikatz_inmemory_detection.yml
rm windows/powershell/powershell_script/posh_ps_cl_invocation_lolscript_count.yml
rm windows/powershell/powershell_script/posh_ps_cl_mutexverifiers_lolscript_count.yml
rm windows/process_creation/proc_creation_win_apt_turla_commands_medium.yml
rm windows/process_creation/proc_creation_win_dnscat2_powershell_implementation.yml
rm windows/process_creation/proc_creation_win_susp_commands_recon_activity.yml
```

3. Run this command to attempt to convert the other remaining rules:
`~/sigma/tools/sigmac -t es-rule -c tools/config/generic/sysmon.yml -c tools/config/winlogbeat-modules-enabled.yml -r rules/windows/`

The error message presented after the process abruptly stops is:
`An unsupported feature is required for this Sigma rule (rules/windows/builtin/system/win_susp_service_installation.yml):`

There is no message after the colon (`:`) character.

For quick reference, the rule causing the error is a recently-added one, and can be found [here](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/system/win_susp_service_installation.yml).

Thank you!

**Comment by thomaspatzke** [comment] 2022-03-24 21:12
Thanks for this finding! I checked it and it appears that the problem is not caused by the backend but already by the rule parsing code. Temporary removal of the code that throws the "unsupported feature" exception results in the real reason:

```
Traceback (most recent call last):
  File "tools/sigmac", line 5, in <module>
    main()
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/sigmac.py", line 318, in main
    parser = SigmaCollectionParser(f, sigmaconfigs, rulefilter, sigmafile)
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/collection.py", line 72, in __init__
    self.parsers.append(SigmaParser(yamldoc, config))
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/rule.py", line 29, in __init__
    self.parse_sigma()
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/rule.py", line 53, in parse_sigma
    condparsed = SigmaConditionParser(self, tokens)
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/condition.py", line 496, in __init__
    self.parsedSearch = self.parseSearch(tokens)
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/condition.py", line 559, in parseSearch
    treenode = operator[2](self.sigmaParser, tok_op, tok_val)
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/condition.py", line 310, in generateOneOf
    return generateXOf(sigma, val, ConditionOR)
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/condition.py", line 297, in generateXOf
    cond.add(NodeSubexpression(sigma.parse_definition(definition)))
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/rule.py", line 86, in parse_definition
    value = apply_modifiers(value, modifiers)
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/modifiers/discovery.py", line 36, in apply_modifiers
    value = modifiers[modifier](value).apply()
  File "/mnt/c/Users/thoma/OneDrive/Devel/sigma/tools/sigma/parser/modifiers/base.py", line 48, in __init__
    raise SigmaModifierValueTypeError
sigma.parser.modifiers.exceptions.SigmaModifierValueTypeError
```

The reason is indeed this part of the Sigma rule you referenced:
```
    ImagePath|contains|all: ' -e'
```

The `all` modifier requires a list, but the rule tries to apply it to a single value, which doesn't makes any sense at all. So your fix in #2852 does exactly what has to be done.

Regarding the other problem, that sigmac outputs this weird error I prefer to close the issue. Sigmac will be discontinued anyways and pySigma/Sigma CLI have a better error handling.

**Closed by thomaspatzke** 2022-03-24 21:12 UTC
